import { StyleSheet } from "react-native";

import { colors, radii } from "./theme";

export const styles = StyleSheet.create({
  page: { flexGrow: 1, gap: 20, padding: 18, paddingBottom: 30 },
  title: { color: colors.ink, fontSize: 30, fontWeight: "800" },
  section: { gap: 10 },
  cardRow: { flexDirection: "row", gap: 9 },
  clippedCard: {
    borderRadius: radii.large,
    overflow: "hidden",
  },
  lastRow: { borderBottomWidth: 0 },
  accentText: { color: colors.teal },
  sectionTitle: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  surface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
  },
  networkCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    justifyContent: "center",
    minHeight: 112,
    padding: 8,
    position: "relative",
  },
  networkCardActive: {
    backgroundColor: colors.blueSoft,
    borderColor: colors.blue,
  },
  button: {
    alignItems: "center",
    backgroundColor: colors.blue,
    borderRadius: radii.medium,
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
  },
  buttonDisabled: { opacity: 0.65 },
  buttonText: { color: colors.surface, fontSize: 15, fontWeight: "700" },
  dialog: { backgroundColor: colors.surface },
  sheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: 14,
    paddingBottom: 28,
    paddingHorizontal: 18,
  },
  detailsCard: {
    borderRadius: radii.medium,
    overflow: "hidden",
  },
  detailRow: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  detailLabel: { color: colors.muted, fontSize: 12 },
  detailValue: { color: colors.ink, fontSize: 12, fontWeight: "600" },
  horizonChoice: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
  },
  horizonChoiceActive: {
    backgroundColor: colors.blueSoft,
    borderColor: colors.blue,
  },
  horizonChoiceText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  horizonChoiceTextActive: { color: colors.blue },
  errorBanner: {
    backgroundColor: colors.redSoft,
    borderColor: colors.errorBorder,
    borderRadius: radii.medium,
    borderWidth: 1,
    padding: 12,
  },
  errorBannerText: { color: colors.errorInk, fontSize: 12 },
  refreshButton: { minHeight: 46, paddingHorizontal: 14 },
  summaryCard: {
    alignItems: "center",
    borderRadius: radii.medium,
    flex: 1,
    gap: 5,
    justifyContent: "center",
    minHeight: 98,
    padding: 8,
  },
  summaryLabel: { color: colors.muted, fontSize: 10, textAlign: "center" },
  summaryValue: { color: colors.blue, fontSize: 20, fontWeight: "800" },
  graphSection: { gap: 14 },
  runScroller: { maxHeight: 272 },
  runRow: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 12,
    minHeight: 68,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  runIcon: {
    alignItems: "center",
    backgroundColor: colors.blueSoft,
    borderRadius: radii.small,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  runCopy: { flex: 1, gap: 2 },
  runDate: { color: colors.ink, fontSize: 13, fontWeight: "700" },
  runMeta: { color: colors.muted, fontSize: 12 },
  emptyRuns: { alignItems: "center", gap: 4, padding: 28 },
  emptyRunsTitle: { color: colors.ink, fontSize: 15, fontWeight: "700" },
  emptyRunsText: { color: colors.muted, fontSize: 12, textAlign: "center" },
  check: { position: "absolute", right: 7, top: 7 },
  networkLabel: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  errorDialog: {
    alignItems: "center",
    borderRadius: radii.large,
    gap: 10,
    padding: 20,
    width: "100%",
  },
  errorDialogIcon: {
    alignItems: "center",
    backgroundColor: colors.redSoft,
    borderRadius: 23,
    height: 46,
    justifyContent: "center",
    width: 46,
  },
  errorDialogTitle: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  errorDialogText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  errorActions: { flexDirection: "row", gap: 9, marginTop: 6, width: "100%" },
  dismissButton: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 46,
  },
  dismissButtonText: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  retryButton: { flex: 1, minHeight: 46 },
  primaryButton: { minHeight: 54, paddingHorizontal: 18 },
  setupButton: { marginTop: "auto" },
  recommendation: {
    alignItems: "center",
    borderRadius: radii.large,
    flexDirection: "row",
    gap: 16,
    minHeight: 112,
    padding: 18,
  },
  successIcon: {
    alignItems: "center",
    backgroundColor: colors.teal,
    borderRadius: 28,
    height: 56,
    justifyContent: "center",
    width: 56,
  },
  recommendationCopy: { flex: 1, gap: 4 },
  eyebrow: { color: colors.muted, fontSize: 13, fontWeight: "600" },
  recommendationText: { color: colors.ink, fontSize: 28, fontWeight: "800" },
  timeline: { flexDirection: "row", gap: 5 },
  timelineCell: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    flex: 1,
    gap: 5,
    justifyContent: "center",
    minHeight: 86,
    minWidth: 43,
    paddingHorizontal: 2,
  },
  timelineHeadCell: { flex: 1.35 },
  timelineCellActive: {
    backgroundColor: colors.tealSoft,
    borderColor: colors.teal,
  },
  timelineLabel: { color: colors.ink, fontSize: 11, fontWeight: "700" },
  timelineBlock: { color: colors.muted, fontSize: 8 },
  timelineOffset: { color: colors.ink, fontSize: 13, fontWeight: "700" },
  timelineTargetLabelSlot: { height: 8 },
  timelineTargetLabel: { fontSize: 7, fontWeight: "800" },
  detailsTitle: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
});
