import { StyleSheet } from "react-native";

import { colors, radii } from "./theme";

export const styles = StyleSheet.create({
  page: { flexGrow: 1, gap: 20, padding: 18, paddingBottom: 30 },
  title: { color: colors.ink, fontSize: 30, fontWeight: "800" },
  section: { gap: 10 },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardRow: { flexDirection: "row", gap: 9 },
  clippedCard: {
    borderRadius: radii.large,
    overflow: "hidden",
  },
  lastRow: { borderBottomWidth: 0 },
  accentText: { color: colors.teal },
  sectionTitle: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  surface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
  },
  networkCard: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    justifyContent: "center",
    padding: 8,
  },
  networkCardActive: {
    backgroundColor: colors.blueSoft,
    borderColor: colors.blue,
  },
  button: {
    alignItems: "center",
    backgroundColor: colors.blue,
    borderRadius: radii.medium,
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
  },
  buttonDisabled: { opacity: 0.65 },
  buttonText: { color: colors.surface, fontSize: 15, fontWeight: "700" },
  dialog: { backgroundColor: colors.surface },
  sheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: 14,
    paddingBottom: 28,
    paddingHorizontal: 18,
  },
  detailsCard: {
    borderRadius: radii.medium,
    overflow: "hidden",
  },
  detailRow: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  detailLabel: { color: colors.muted, fontSize: 12 },
  detailValue: { color: colors.ink, fontSize: 12, fontWeight: "600" },
  horizonSlider: { height: 28, width: "100%" },

  networkBadge: {
    alignItems: "center",
    backgroundColor: colors.blueSoft,
    borderRadius: 14,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  networkBadgeText: { color: colors.blue, fontSize: 11, fontWeight: "700" },
  networkSheet: { paddingTop: 18 },
  networkSheetTitle: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  networkOption: {
    backgroundColor: colors.background,
    minHeight: 88,
  },
  networkOptionText: { color: colors.muted, fontSize: 11, fontWeight: "700" },
  networkOptionTextActive: { color: colors.blue },
  storageError: {
    backgroundColor: colors.redSoft,
    borderColor: colors.errorBorder,
    borderRadius: radii.medium,
    borderWidth: 1,
    padding: 12,
  },
  storageErrorText: { color: colors.errorInk, fontSize: 12 },
  refreshButton: { minHeight: 46, paddingHorizontal: 14 },
  summaryCard: {
    alignItems: "center",
    borderRadius: radii.medium,
    flex: 1,
    gap: 5,
    justifyContent: "center",
    minHeight: 98,
    padding: 8,
  },
  summaryLabel: { color: colors.muted, fontSize: 10, textAlign: "center" },
  summaryValue: { color: colors.blue, fontSize: 20, fontWeight: "800" },
  graphSection: { gap: 14 },
  graphSliderCard: {
    borderRadius: radii.large,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chartCards: { gap: 12 },
  chartCard: {
    borderRadius: radii.large,
    gap: 14,
    overflow: "hidden",
    padding: 14,
  },
  chartTitle: { color: colors.ink, fontSize: 15, fontWeight: "700" },
  graph: { gap: 2 },
  graphAxisText: { color: colors.muted, fontSize: 9 },
  graphXAxisTitle: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: "600",
    marginTop: 3,
    textAlign: "center",
  },
  graphLegend: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  graphLegendDot: { borderRadius: 4, height: 7, marginLeft: 5, width: 7 },
  graphImmediateDot: { backgroundColor: colors.amberSoft },
  graphKairosDot: { backgroundColor: colors.blue },
  graphLegendLabel: { color: colors.muted, fontSize: 8 },
  emptyGraph: {
    alignItems: "center",
    height: 184,
    justifyContent: "center",
    padding: 24,
  },
  emptyGraphTitle: { color: colors.ink, fontSize: 16, fontWeight: "700" },
  emptyGraphText: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 5,
    textAlign: "center",
  },
  runScroller: { maxHeight: 272 },
  runRow: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 12,
    minHeight: 68,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  runIcon: {
    alignItems: "center",
    backgroundColor: colors.blueSoft,
    borderRadius: radii.small,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  runCopy: { flex: 1, gap: 2 },
  runDate: { color: colors.ink, fontSize: 13, fontWeight: "700" },
  runMeta: { color: colors.muted, fontSize: 12 },
  emptyRuns: { alignItems: "center", gap: 4, padding: 28 },
  emptyRunsTitle: { color: colors.ink, fontSize: 15, fontWeight: "700" },
  emptyRunsText: { color: colors.muted, fontSize: 12, textAlign: "center" },
  runDialog: { paddingTop: 9 },
  handle: {
    alignSelf: "center",
    backgroundColor: colors.border,
    borderRadius: 3,
    height: 5,
    width: 48,
  },
  dialogHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dialogTitle: { color: colors.ink, fontSize: 24, fontWeight: "800" },
  dialogDate: { color: colors.muted, fontSize: 13, marginTop: 2 },
  selectionSummary: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    flexDirection: "row",
    padding: 12,
  },
  selectionItem: { flex: 1, gap: 3 },
  detailStrong: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  groupTitle: { color: colors.blue, fontSize: 15, fontWeight: "700" },
  closeButton: { minHeight: 50 },

  inferenceNetworkCard: {
    backgroundColor: colors.surface,
    minHeight: 112,
    position: "relative",
  },
  check: { position: "absolute", right: 7, top: 7 },
  networkLabel: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  windowCard: {
    borderRadius: radii.large,
    gap: 12,
    padding: 14,
  },
  windowTrack: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  windowHead: { alignItems: "center", gap: 3, paddingTop: 12, width: 38 },
  windowHeadNode: {
    alignItems: "center",
    backgroundColor: colors.navy,
    borderRadius: 8,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  windowHeadLabel: { color: colors.muted, fontSize: 9, fontWeight: "600" },
  predictionGroup: { flex: 1, gap: 3 },
  predictionSpace: {
    backgroundColor: colors.blueSoft,
    borderColor: colors.blue,
    borderRadius: radii.medium,
    borderStyle: "dashed",
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  predictionSpaceLabel: {
    color: colors.blue,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.6,
    textAlign: "center",
    textTransform: "uppercase",
  },
  predictionChain: {
    flexDirection: "row",
    justifyContent: "space-between",
    position: "relative",
  },
  predictionLine: {
    backgroundColor: colors.predictionLine,
    height: 2,
    left: 13,
    position: "absolute",
    right: 13,
    top: 13,
  },
  predictionBlock: { alignItems: "center", flex: 1, gap: 1 },
  predictionNode: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.blue,
    borderRadius: 7,
    borderWidth: 1,
    height: 27,
    justifyContent: "center",
    width: 27,
  },
  predictionNodeLabel: { color: colors.blue, fontSize: 8, fontWeight: "800" },
  errorDialog: {
    alignItems: "center",
    borderRadius: radii.large,
    gap: 10,
    padding: 20,
    width: "100%",
  },
  errorDialogIcon: {
    alignItems: "center",
    backgroundColor: colors.redSoft,
    borderRadius: 23,
    height: 46,
    justifyContent: "center",
    width: 46,
  },
  errorDialogTitle: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  errorDialogText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  errorActions: { flexDirection: "row", gap: 9, marginTop: 6, width: "100%" },
  dismissButton: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 46,
  },
  dismissButtonText: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  retryButton: { flex: 1, minHeight: 46 },
  primaryButton: { minHeight: 54, paddingHorizontal: 18 },
  setupButton: { marginTop: "auto" },
  recommendation: {
    alignItems: "center",
    borderLeftColor: colors.teal,
    borderLeftWidth: 5,
    borderRadius: radii.large,
    flexDirection: "row",
    gap: 16,
    minHeight: 112,
    padding: 18,
  },
  successIcon: {
    alignItems: "center",
    backgroundColor: colors.teal,
    borderRadius: 28,
    height: 56,
    justifyContent: "center",
    width: 56,
  },
  recommendationCopy: { flex: 1, gap: 4 },
  eyebrow: { color: colors.muted, fontSize: 13, fontWeight: "600" },
  recommendationText: { color: colors.ink, fontSize: 28, fontWeight: "800" },
  timeline: { flexDirection: "row", gap: 5 },
  timelineCell: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: 1,
    flex: 1,
    gap: 5,
    justifyContent: "center",
    minHeight: 86,
    minWidth: 43,
    paddingHorizontal: 2,
  },
  timelineHeadCell: { flex: 1.35 },
  timelineCellActive: {
    backgroundColor: colors.tealSoft,
    borderColor: colors.teal,
  },
  timelineLabel: { color: colors.ink, fontSize: 11, fontWeight: "700" },
  timelineBlock: { color: colors.muted, fontSize: 8 },
  timelineOffset: { color: colors.ink, fontSize: 13, fontWeight: "700" },
  timelineTargetLabel: {
    color: colors.transparent,
    fontSize: 7,
    fontWeight: "800",
  },
  detailsTitle: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
});
